server.port=9092

spring.data.redis.url=redis-16709.c44.us-east-1-2.ec2.redns.redis-cloud.com
spring.data.redis.port=16709
spring.data.redis.username=default
spring.data.redis.password=x83DhsVCd3x87E2ccDO9CDJX7Zyblqkp
